Traceback (most recent call last):
  File "/home/jl5824/pfs-neural-net/graph.py", line 101, in <module>
    graph = to_Graph(indices[mask], utils[mask])
                                    ~~~~~^^^^^^
IndexError: boolean index did not match indexed array along axis 0; size of axis is 12 but size of corresponding boolean axis is 477597
Traceback (most recent call last):
  File "/home/jl5824/pfs-neural-net/train.py", line 116, in <module>
    graphs = [torch.load(f'graphs/graph-{i}.pt') for i in range(ntrain)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl5824/.conda/envs/torch-gnn/lib/python3.12/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl5824/.conda/envs/torch-gnn/lib/python3.12/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jl5824/.conda/envs/torch-gnn/lib/python3.12/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'graphs/graph-0.pt'
